app = "url-link"
primary_region = "fra"

[build]
  dockerfile = "./Dockerfile"

[deploy]
  release_command = "echo Skip release"

[http_service]
  internal_port = 80
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  max_machines_running = 1

  processes = ["app"]

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1